site_name: Ludwig's Notebook

repo_url: https://github.com/cs32963/Notebook
repo_name: cs32963/Notebook

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# FIXME: social cairo error
plugins:
  - blog:
      categories_allowed:
        - 技术
        - 基础
        - 项目
        - 生活
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - search:
      separator: '[\s\u200b\-]'
  # - social

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/cs32963

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 <a href="https://github.com/cs32963"  target="_blank" rel="noopener">Ludwig</a>

nav:
  - 主页: 
    - 写在前面: index.md
    - 学生生涯反思: retrospect.md
    - 如何成为优秀的算法工程师: become_better.md
  - 课程笔记:
    - 计算机系统导论:
      - 引言: notes/cs_intro/index.md
    - 操作系统:
      - 引言: notes/os/index.md
  - 编程语言:
    - Python:
      - 引言: programming_languages/python/index.md
      - Craftsmanship: programming_languages/python/craftsmanship.md
    - C++:
      - 引言: programming_languages/c++/index.md
  - 算法学习:
    - 坚持刷算法题的好处: algorithms/index.md
    - 学习路线: algorithms/roadmap.md
    - 常见算法:
      - 动态规划: algorithms/dp.md
      - 贪心: algorithms/greedy.md
      - 二分: algorithms/binary_search.md
      - 双指针/滑动窗口: algorithms/two_pointers.md
      - 单调栈: algorithms/monotonic_stack.md
      - 搜索: algorithms/search.md
      - 位运算: algorithms/bitwise_ops.md
      - 并查集: algorithms/union_find.md
    - 有趣的问题:
      - 蚂蚁行进问题: algorithms/ants.md
      - 约瑟夫问题: algorithms/josephus.md
    - 题单:
      - Codeforces: algorithms/codeforces_problem_list.md
      - LeetCode: algorithms/leetcode_problem_list.md
  - 日常笔记:
    - 访谈与演讲: regular/talks.md
  - 博客:
    - blog/index.md
